name: "SIWYS-JS Pre-Merge Quality Check Services"
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=8192
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Sanitize branch name
        id: branch
        uses: onliner/sanitize-branch-name@v1

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Use Yarn Cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test
        
      - name: Run builds
        run: yarn build
