name: Lint PR name
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Files
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@selfidhq"
      - name: Install Dependencies
        run: yarn add @commitlint/config-conventional@17 --ignore-workspace-root-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: JulienKode/pull-request-name-linter-action@v20.1.0
